kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: alpha-prod
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-secret-reader
  namespace: alpha-prod
subjects:
- kind: ServiceAccount
  name: default
  namespace: alpha-prod
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
