apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  labels:
    app: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "weather"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "info"
        dapr.io/sidecar-liveness-probe-period-seconds: "10"
        dapr.io/sidecar-readiness-probe-period-seconds: "10"
    spec:
      containers:
      - name: weather
        image: ghcr.io/mludeiro/alpha.weather:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
