apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-token
  labels:
    type: local
    app: postgres-token
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-identity
  labels:
    type: local
    app: postgres-identity
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql